export const TURATH_BOOKS = [
    // Kutub Sittah & Tis'ah
    { id: 'bukhari', name: 'صحيح البخاري', category: 'hadith' },
    { id: 'muslim', name: 'صحيح مسلم', category: 'hadith' },
    { id: 'abudawud', name: 'سنن أبي داود', category: 'hadith' },
    { id: 'tirmidhi', name: 'سنن الترمذي', category: 'hadith' },
    { id: 'nasai', name: 'سنن النسائي', category: 'hadith' },
    { id: 'ibnmajah', name: 'سنن ابن ماجه', category: 'hadith' },
    { id: 'muwatta', name: 'الموطأ لمالك', category: 'hadith' },
    { id: 'ahmad', name: 'مسند أحمد', category: 'hadith' },
    { id: 'darimi', name: 'سنن الدارمي', category: 'hadith' },
    // Tafsir
    { id: 'tafsir_tabari', name: 'تفسير الطبري', category: 'tafsir' },
    { id: 'tafsir_ibnkathir', name: 'تفسير ابن كثير', category: 'tafsir' },
    { id: 'tafsir_qurtubi', name: 'تفسير القرطبي', category: 'tafsir' },
    { id: 'tafsir_baghawi', name: 'تفسير البغوي', category: 'tafsir' },
    { id: 'tafsir_saadi', name: 'تفسير السعدي', category: 'tafsir' },
    { id: 'tafsir_jalalain', name: 'تفسير الجلالين', category: 'tafsir' },
    { id: 'durr_manthur', name: 'الدر المنثور', category: 'tafsir' },
    // Fiqh
    { id: 'umm', name: 'الأم للشافعي', category: 'fiqh' },
    { id: 'risalah', name: 'الرسالة للشافعي', category: 'fiqh' },
    { id: 'majmu', name: 'المجموع شرح المهذب', category: 'fiqh' },
    { id: 'mugni', name: 'المغني لابن قدامة', category: 'fiqh' },
    { id: 'rawdah', name: 'روضة الطالبين', category: 'fiqh' },
    { id: 'minhaj', name: 'منهاج الطالبين', category: 'fiqh' },
    { id: 'badaitsanai', name: 'بدائع الصنائع', category: 'fiqh' },
    { id: 'hidayah', name: 'الهداية في شرح البداية', category: 'fiqh' },
    { id: 'mudawwanah', name: 'المدونة', category: 'fiqh' },
    { id: 'muhalla', name: 'المحلى بالآثار', category: 'fiqh' },
    { id: 'naylul_autar', name: 'نيل الأوطار', category: 'fiqh' },
    { id: 'subul_salam', name: 'سبل السلام', category: 'fiqh' },
    // Aqidah & Fatawa
    { id: 'majmu_fatawa', name: 'مجموع الفتاوى', category: 'aqidah' },
    { id: 'aqidah_wasitiyah', name: 'العقيدة الواسطية', category: 'aqidah' },
    { id: 'aqidah_tahawiyah', name: 'العقيدة الطحاوية', category: 'aqidah' },
    { id: 'lumatul_itiqad', name: 'لمعة الاعتقاد', category: 'aqidah' },
    { id: 'kitab_tauhid', name: 'كتاب التوحيد', category: 'aqidah' },
    // Tarikh & Siyar
    { id: 'siyar', name: 'سير أعلام النبلاء', category: 'tarikh' },
    { id: 'bidaya', name: 'البداية والنهاية', category: 'tarikh' },
    { id: 'tarikh_tabari', name: 'تاريخ الطبري', category: 'tarikh' },
    { id: 'kamil_fi_tarikh', name: 'الكامل في التاريخ', category: 'tarikh' },
    { id: 'hilyatul_auliya', name: 'حلية الأولياء', category: 'tarikh' },
    { id: 'tabaqat_kubra', name: 'الطبقات الكبرى', category: 'tarikh' },
    // Ulumul Quran & Hadith
    { id: 'itgan', name: 'الإتقان في علوم القرآن', category: 'ulum' },
    { id: 'burhan', name: 'البرهان في علوم القرآن', category: 'ulum' },
    { id: 'muqaddimah_ibnsalah', name: 'مقدمة ابن الصلاح', category: 'ulum' },
    { id: 'nuzhatul_nazar', name: 'نزهة النظر', category: 'ulum' },
    { id: 'alfiyah_suyuti', name: 'ألفية السيوطي', category: 'ulum' },
    // Others
    { id: 'ihya', name: 'إحياء علوم الدين', category: 'tazkiyah' },
    { id: 'riyad_salihin', name: 'رياض الصالحين', category: 'hadith' },
    { id: 'adhkar', name: 'الأذكار للنووي', category: 'hadith' },
    { id: 'bulugh_maram', name: 'بلوغ المرام', category: 'hadith' },
    { id: 'zad_maad', name: 'زاد المعاد', category: 'tarikh' },
    { id: 'igatha_lahfan', name: 'إغاثة اللهفان', category: 'tazkiyah' },
    { id: 'daii_dawa', name: 'الداء والدواء', category: 'tazkiyah' }
];

export const TURATH_AUTHORS = [
    { id: 'bukhari', name: 'محمد بن إسماعيل البخاري', death: 256, madhhab: 'shafii' }, // Generally considered Shafii or Mujtahid
    { id: 'muslim', name: 'مسلم بن الحجاج', death: 261, madhhab: 'shafii' },
    { id: 'abudawud', name: 'أبو داود السجستاني', death: 275, madhhab: 'hanbali' }, // Or Shafii
    { id: 'tirmidhi', name: 'محمد بن عيسى الترمذي', death: 279, madhhab: 'shafii' }, // Or Independent
    { id: 'nasai', name: 'أحمد بن شعيب النسائي', death: 303, madhhab: 'shafii' },
    { id: 'ibnmajah', name: 'ابن ماجه القزويني', death: 273, madhhab: 'shafii' },
    { id: 'malik', name: 'مالك بن أنس', death: 179, madhhab: 'maliki' },
    { id: 'ahmad', name: 'أحمد بن حنبل', death: 241, madhhab: 'hanbali' },
    { id: 'shafii', name: 'محمد بن إدريس الشافعي', death: 204, madhhab: 'shafii' },
    { id: 'abuhanifah', name: 'أبو حنيفة النعمان', death: 150, madhhab: 'hanafi' },
    { id: 'thawri', name: 'سفيان الثوري', death: 161, madhhab: 'mujtahid' },
    { id: 'awzai', name: 'الأوزاعي', death: 157, madhhab: 'mujtahid' },
    { id: 'nawawi', name: 'يحيى بن شرف النووي', death: 676, madhhab: 'shafii' },
    { id: 'ibntaymiyyah', name: 'ابن تيمية', death: 728, madhhab: 'hanbali' },
    { id: 'ibnqayyim', name: 'ابن القيم', death: 751, madhhab: 'hanbali' },
    { id: 'dhahabi', name: 'الذهبي', death: 748, madhhab: 'shafii' },
    { id: 'ibnkathir', name: 'ابن كثير', death: 774, madhhab: 'shafii' },
    { id: 'tabari', name: 'الطبري', death: 310, madhhab: 'mujtahid' },
    { id: 'qurtubi', name: 'القرطبي', death: 671, madhhab: 'maliki' },
    { id: 'ibnhajar', name: 'ابن حجر العسقلاني', death: 852, madhhab: 'shafii' },
    { id: 'suyuti', name: 'جلال الدين السيوطي', death: 911, madhhab: 'shafii' },
    { id: 'ghazali', name: 'أبو حامد الغزالي', death: 505, madhhab: 'shafii' },
    { id: 'ibnqudama', name: 'ابن قدامة المقدسي', death: 620, madhhab: 'hanbali' },
    { id: 'ibnrajab', name: 'ابn رجب الحنبلي', death: 795, madhhab: 'hanbali' },
    { id: 'albani', name: 'الألباني', death: 1420, madhhab: 'salafi' },
    { id: 'binbaz', name: 'بين باز', death: 1420, madhhab: 'salafi' },
    { id: 'uthaymeen', name: 'ابن عثيمين', death: 1421, madhhab: 'salafi' },
    { id: 'shawkani', name: 'الشوكاني', death: 1250, madhhab: 'mujtahid' },
    { id: 'sanani', name: 'الصنعاني', death: 1182, madhhab: 'mujtahid' },
    { id: 'ibnabdilbarr', name: 'ابن عبد البر', death: 463, madhhab: 'maliki' },
    { id: 'baghawi', name: 'البغوي', death: 516, madhhab: 'shafii' },
    { id: 'ibnjozi', name: 'ابن الجوزي', death: 597, madhhab: 'hanbali' },
    { id: 'ibnhazm', name: 'ابن حزم', death: 456, madhhab: 'dhahiri' }
];
